import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG PQueue on 20250415
/**
 * These are the "State" tests of the group "Size"
 * of the "PQueue" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250408
 */
public class PQueueSizeStateTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <>.size() -> <>
     */
    @Test
    public void empty() {
        PQueue o = PQueueFactory.build("<>");
        String expected = "<>";
        o.size();
        String actual = o.toString();
        String pi = "<>.size() -> <>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <4,2,3,1>.size() -> <4,2,3,1>
     */
    @Test
    public void fourNode() {
        PQueue o = PQueueFactory.build("<4,2,3,1>");
        String expected = "<4,2,3,1>";
        o.size();
        String actual = o.toString();
        String pi = "<4,2,3,1>.size() -> <4,2,3,1>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <10,9,8,6,7>.size() -> <10,9,8,6,7>
     */
    @Test
    public void five() {
        PQueue o = PQueueFactory.build("<10,9,8,6,7>");
        String expected = "<10,9,8,6,7>";
        o.size();
        String actual = o.toString();
        String pi = "<10,9,8,6,7>.size() -> <10,9,8,6,7>";
        assertEquals(pi, expected, actual);
    }

}