import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import edu.cnu.cnuassert.CNUThrowingRunnable;
//
// correct these imports if needed and add any missing exception imports here.
import java.util.NoSuchElementException;
//

// GENERATED BY ATA3.0/20240730 FROM ASG PQueue on 20250415
/**
 * These are the "Exception" tests of the group "Dequeue"
 * of the "PQueue" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250408
 */
public class PQueueDequeueExceptionTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <>.dequeue() !! NoSuchElementException
     */
    @Test
    public void empty() {
        PQueue o = PQueueFactory.build("<>");
        Class<? extends Throwable> expected = NoSuchElementException.class;
        CNUThrowingRunnable l = () -> o.dequeue();
        String pi = "<>.dequeue() !! NoSuchElementException";
        assertThrows(pi, expected, l);
    }

}