import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG PQueue on 20250415
/**
 * These are the "State" tests of the group "SetToIntArray"
 * of the "PQueue" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250408
 */
public class PQueueSetToIntArrayStateTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <44,22,32,12>.setTo(a) -> <5,3,4>
     */
    @Test
    public void fourNode() {
        PQueue o = PQueueFactory.build("<44,22,32,12>");
        int[] a = {3, 5, 4};
        String expected = "<5,3,4>";
        o.setTo(a);
        String actual = o.toString();
        String pi = "<44,22,32,12>.setTo(a) -> <5,3,4>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <>.setTo(a) -> <10,5,8>
     */
    @Test
    public void empty() {
        PQueue o = PQueueFactory.build("<>");
        int[] a = {10, 5, 8};
        String expected = "<10,5,8>";
        o.setTo(a);
        String actual = o.toString();
        String pi = "<>.setTo(a) -> <10,5,8>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <12,9,10,6,7,8>.setTo(a) -> <8,6,7,3,4,2>
     */
    @Test
    public void six() {
        PQueue o = PQueueFactory.build("<12,9,10,6,7,8>");
        int[] a = {8, 6, 7, 3, 4, 2};
        String expected = "<8,6,7,3,4,2>";
        o.setTo(a);
        String actual = o.toString();
        String pi = "<12,9,10,6,7,8>.setTo(a) -> <8,6,7,3,4,2>";
        assertEquals(pi, expected, actual);
    }

}