import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG PQueue on 20250415
/**
 * These are the "State" tests of the group "ToString"
 * of the "PQueue" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250408
 */
public class PQueueToStringStateTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <5,4,3,2,1>.toString() -> <5,4,3,2,1>
     */
    @Test
    public void fiveNode() {
        PQueue o = PQueueFactory.build("<5,4,3,2,1>");
        String expected = "<5,4,3,2,1>";
        o.toString();
        String actual = o.toString();
        String pi = "<5,4,3,2,1>.toString() -> <5,4,3,2,1>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <>.toString() -> <>
     */
    @Test
    public void empty() {
        PQueue o = PQueueFactory.build("<>");
        String expected = "<>";
        o.toString();
        String actual = o.toString();
        String pi = "<>.toString() -> <>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <4,2,3,1>.toString() -> <4,2,3,1>
     */
    @Test
    public void fourNode() {
        PQueue o = PQueueFactory.build("<4,2,3,1>");
        String expected = "<4,2,3,1>";
        o.toString();
        String actual = o.toString();
        String pi = "<4,2,3,1>.toString() -> <4,2,3,1>";
        assertEquals(pi, expected, actual);
    }

}