// GENERATED BY ATA3.0/20240730 FROM ASG PQueue on 20250415
/**
 * Static Factory method(s) that return an object with a specified state. Should
 * be abstract since it only has static methods but Web-CAT flags code coverage
 * because it's not instantiated.
 * 
 * @author asand
 * @version 20250408
 */
public class PQueueFactory {

    /**
     * Returns an object of the given state s.
     * 
     * @param s
     *            state string of the desired object
     * @return object with state s
     */
    public static PQueue build(String s) {



        // instantiate the object to be returned.
       
        PQueue o = new HeapPQueue();

        // set o to the specified state (s)
        switch (s) {
            case "<5,4,3,2,1>" :
                o.enqueue(5);
                o.enqueue(4);
                o.enqueue(3);
                o.enqueue(2);
                o.enqueue(1);
                break;
            case "<>" :
                break;
            case "<12,9,10,6,7,8>" :
                o.enqueue(12);
                o.enqueue(9);
                o.enqueue(10);
                o.enqueue(6);
                o.enqueue(7);
                o.enqueue(8);
                break;
            case "<44,22,32,12>" :
                o.enqueue(44);
                o.enqueue(22);
                o.enqueue(32);
                o.enqueue(12);
                break;
            case "<4,2,3,1>" :
                o.enqueue(4);
                o.enqueue(2);
                o.enqueue(3);
                o.enqueue(1);
                break;
            case "<10,5,8>" :
                o.enqueue(10);
                o.enqueue(5);
                o.enqueue(8);
                break;
            case "<10,9,8,6,7>" :
                o.enqueue(10);
                o.enqueue(9);
                o.enqueue(8);
                o.enqueue(6);
                o.enqueue(7);
                break;

            // s was not one of the states specified in Asg PQueue
            default:
                String fmt =
                    "Problem in PQueueFactory.java: unhandled state(%s)";
                throw new IllegalArgumentException(String.format(fmt, s));
        }

        return o;
    }

}