import static org.junit.Assert.*;
import org.junit.Test;

// GENERATED BY ATA3.0/20240730 FROM ASG CharBst on 20250325
/**
 * Tests to minimize Web-CAT code coverage subtractions.
 * 
 * @author asand
 * @version 20250316
 */
public class CharBstFactoryTests {

    /**
     * Web-CAT subtracts for code coverage of an uninstantiated class. The state
     * factory class only has static methods so shouldn't be instantiated.
     */
    @Test
    public void stateFactoryInstantiates() {
        CharBstFactory sf = new CharBstFactory();
        assertNotNull(sf);
    }


    /**
     * Web-CAT subtracts for code coverage of an uninstantiated class. The state
     * factory class checks for undefined state strings, so. should test with
     * invalid state string.
     */
    @Test
    public void stateFactoryThrowsOnUndefined() {
        Class<? extends Throwable> expected = IllegalArgumentException.class;
        try {
            CharBstFactory.build("invalidstate3.0/20240730");
            fail("ATA error: no IAE on invalid state");
        }
        catch (IllegalArgumentException e) {
            assertEquals(expected, e.getClass());
        }
    }
}