import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG CharBst on 20250325
/**
 * These are the "State" tests of the group "RemoveChar"
 * of the "CharBst" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250316
 */
public class CharBstRemoveCharStateTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <a,b,c>.remove('c') -> <a,b>
     */
    @Test
    public void isc() {
        CharBst o = CharBstFactory.build("<a,b,c>");
        String expected = "<a,b>";
        o.remove('c');
        String actual = o.toString();
        String pi = "<a,b,c>.remove('c') -> <a,b>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,c,d,e>.remove('c') -> <a,b,d,e>
     */
    @Test
    public void fivewith() {
        CharBst o = CharBstFactory.build("<a,b,c,d,e>");
        String expected = "<a,b,d,e>";
        o.remove('c');
        String actual = o.toString();
        String pi = "<a,b,c,d,e>.remove('c') -> <a,b,d,e>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <c>.remove('c') -> <>
     */
    @Test
    public void justc() {
        CharBst o = CharBstFactory.build("<c>");
        String expected = "<>";
        o.remove('c');
        String actual = o.toString();
        String pi = "<c>.remove('c') -> <>";
        assertEquals(pi, expected, actual);
    }

}