// GENERATED BY ATA3.0/20240730 FROM ASG CharBst on 20250325
/**
 * Static Factory method(s) that return an object with a specified state. Should
 * be abstract since it only has static methods but Web-CAT flags code coverage
 * because it's not instantiated.
 * 
 * @author asand
 * @version 20250316
 */
public class CharBstFactory {

    /**
     * Returns an object of the given state s.
     * 
     * @param s
     *            state string of the desired object
     * @return object with state s
     */
    public static CharBst build(String s) {

        // instantiate the object to be returned.
        CharBst o = new CharNodeBst();

        // set o to the specified state (s)
        switch (s) {
            case "<>" :
                break;
            case "<c>" :
                o.insert('c');
                break;
            case "<s,a,f,t,g,j>" :
                o.insert('s');
                o.insert('a');
                o.insert('f');
                o.insert('t');
                o.insert('g');
                o.insert('j');
                break;
            case "<a,b,c>" :
                o.insert('a');
                o.insert('b');
                o.insert('c');
                break;
            case "<a,b,c,d,e>" :
                o.insert('a');
                o.insert('b');
                o.insert('c');
                o.insert('d');
                o.insert('e');
                break;
            case "<a,b,d,e,f>" :
                o.insert('a');
                o.insert('b');
                o.insert('d');
                o.insert('e');
                o.insert('f');
                break;
            case "<a,b,d>" :
                o.insert('a');
                o.insert('b');
                o.insert('d');
                break;

            // s was not one of the states specified in Asg CharBst
            default:
                String fmt =
                    "Problem in CharBstFactory.java: unhandled state(%s)";
                throw new IllegalArgumentException(String.format(fmt, s));
        }

        return o;
    }

}