import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG CharBst on 20250325
/**
 * These are the "Value" tests of the group "Pre"
 * of the "CharBst" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250316
 */
public class CharBstPreValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <a,b,c>.pre() == "a,b,c"
     */
    @Test
    public void isc() {
        CharBst o = CharBstFactory.build("<a,b,c>");
        String expected = "a,b,c";
        String actual = o.pre();
        String pi = "<a,b,c>.pre() == \"a,b,c\"";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,d>.pre() == "a,b,d"
     */
    @Test
    public void isnotc() {
        CharBst o = CharBstFactory.build("<a,b,d>");
        String expected = "a,b,d";
        String actual = o.pre();
        String pi = "<a,b,d>.pre() == \"a,b,d\"";
        assertEquals(pi, expected, actual);
    }


    /**
     * <>.pre() == ""
     */
    @Test
    public void empty() {
        CharBst o = CharBstFactory.build("<>");
        String expected = "";
        String actual = o.pre();
        String pi = "<>.pre() == \"\"";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,c,d,e>.pre() == "a,b,c,d,e"
     */
    @Test
    public void fivewith() {
        CharBst o = CharBstFactory.build("<a,b,c,d,e>");
        String expected = "a,b,c,d,e";
        String actual = o.pre();
        String pi = "<a,b,c,d,e>.pre() == \"a,b,c,d,e\"";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,d,e,f>.pre() == "a,b,d,e,f"
     */
    @Test
    public void fivewithout() {
        CharBst o = CharBstFactory.build("<a,b,d,e,f>");
        String expected = "a,b,d,e,f";
        String actual = o.pre();
        String pi = "<a,b,d,e,f>.pre() == \"a,b,d,e,f\"";
        assertEquals(pi, expected, actual);
    }


    /**
     * <s,a,f,t,g,j>.pre() == "s,a,f,g,j,t"
     */
    @Test
    public void diff() {
        CharBst o = CharBstFactory.build("<s,a,f,t,g,j>");
        String expected = "s,a,f,g,j,t";
        String actual = o.pre();
        String pi = "<s,a,f,t,g,j>.pre() == \"s,a,f,g,j,t\"";
        assertEquals(pi, expected, actual);
    }


    /**
     * <c>.pre() == "c"
     */
    @Test
    public void justc() {
        CharBst o = CharBstFactory.build("<c>");
        String expected = "c";
        String actual = o.pre();
        String pi = "<c>.pre() == \"c\"";
        assertEquals(pi, expected, actual);
    }

}