import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG CharBst on 20250325
/**
 * These are the "Value" tests of the group "Size"
 * of the "CharBst" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250316
 */
public class CharBstSizeValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <>.size() == 0
     */
    @Test
    public void empty() {
        CharBst o = CharBstFactory.build("<>");
        int expected = 0;
        int actual = o.size();
        String pi = "<>.size() == 0";
        assertEquals(pi, expected, actual);
    }


    /**
     * <c>.size() == 1
     */
    @Test
    public void justc() {
        CharBst o = CharBstFactory.build("<c>");
        int expected = 1;
        int actual = o.size();
        String pi = "<c>.size() == 1";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,c>.size() == 3
     */
    @Test
    public void isc() {
        CharBst o = CharBstFactory.build("<a,b,c>");
        int expected = 3;
        int actual = o.size();
        String pi = "<a,b,c>.size() == 3";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,c,d,e>.size() == 5
     */
    @Test
    public void fivewith() {
        CharBst o = CharBstFactory.build("<a,b,c,d,e>");
        int expected = 5;
        int actual = o.size();
        String pi = "<a,b,c,d,e>.size() == 5";
        assertEquals(pi, expected, actual);
    }

}