import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import edu.cnu.cnuassert.CNUThrowingRunnable;
//
// correct these imports if needed and add any missing exception imports here.
//

// GENERATED BY ATA3.0/20240730 FROM ASG CharBst on 20250325
/**
 * These are the "Exception" tests of the group "InsertChar"
 * of the "CharBst" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250316
 */
public class CharBstInsertCharExceptionTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <a,b,c>.insert('c') !! IllegalArgumentException
     */
    @Test
    public void three() {
        CharBst o = CharBstFactory.build("<a,b,c>");
        Class<? extends Throwable> expected = IllegalArgumentException.class;
        CNUThrowingRunnable l = () -> o.insert('c');
        String pi = "<a,b,c>.insert('c') !! IllegalArgumentException";
        assertThrows(pi, expected, l);
    }


    /**
     * <c>.insert('c') !! IllegalArgumentException
     */
    @Test
    public void justc() {
        CharBst o = CharBstFactory.build("<c>");
        Class<? extends Throwable> expected = IllegalArgumentException.class;
        CNUThrowingRunnable l = () -> o.insert('c');
        String pi = "<c>.insert('c') !! IllegalArgumentException";
        assertThrows(pi, expected, l);
    }

}