import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * These are the "ValueTrue" tests of the group "EqualsObject"
 * of the "List" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListEqualsObjectValueTrueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <>.equals(o) == true
     */
    @Test
    public void same() {
        List o = ListFactory.build("<>");
        boolean expected = true;
        boolean actual = o.equals(o);
        String pi = "<>.equals(o) == true";
        assertEquals(pi, expected, actual);
    }


    /**
     * <>.equals(x) == true
     */
    @Test
    public void empty() {
        List o = ListFactory.build("<>");
        List x = ListFactory.build("<>");
        boolean expected = true;
        boolean actual = o.equals(x);
        String pi = "<>.equals(x) == true";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a>.equals(x) == true
     */
    @Test
    public void one() {
        List o = ListFactory.build("<a>");
        List x = ListFactory.build("<a>");
        boolean expected = true;
        boolean actual = o.equals(x);
        String pi = "<a>.equals(x) == true";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.equals(x) == true
     */
    @Test
    public void five() {
        List o = ListFactory.build("<abcde>");
        List x = ListFactory.build("<abcde>");
        boolean expected = true;
        boolean actual = o.equals(x);
        String pi = "<abcde>.equals(x) == true";
        assertEquals(pi, expected, actual);
    }

}