import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * These are the "State" tests of the group "InsertCharInt"
 * of the "List" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListInsertCharIntStateTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <>.insert('a',0) -> <a>
     */
    @Test
    public void emptyAt0() {
        List o = ListFactory.build("<>");
        String expected = "<a>";
        o.insert('a', 0);
        String actual = o.toString();
        String pi = "<>.insert('a',0) -> <a>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a>.insert('b',0) -> <ba>
     */
    @Test
    public void oneAt0() {
        List o = ListFactory.build("<a>");
        String expected = "<ba>";
        o.insert('b', 0);
        String actual = o.toString();
        String pi = "<a>.insert('b',0) -> <ba>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a>.insert('b',1) -> <ab>
     */
    @Test
    public void oneAt1() {
        List o = ListFactory.build("<a>");
        String expected = "<ab>";
        o.insert('b', 1);
        String actual = o.toString();
        String pi = "<a>.insert('b',1) -> <ab>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.insert('x',0) -> <xabcde>
     */
    @Test
    public void fiveAt0() {
        List o = ListFactory.build("<abcde>");
        String expected = "<xabcde>";
        o.insert('x', 0);
        String actual = o.toString();
        String pi = "<abcde>.insert('x',0) -> <xabcde>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.insert('x',2) -> <abxcde>
     */
    @Test
    public void fiveAt2() {
        List o = ListFactory.build("<abcde>");
        String expected = "<abxcde>";
        o.insert('x', 2);
        String actual = o.toString();
        String pi = "<abcde>.insert('x',2) -> <abxcde>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.insert('x',5) -> <abcdex>
     */
    @Test
    public void fiveAt5() {
        List o = ListFactory.build("<abcde>");
        String expected = "<abcdex>";
        o.insert('x', 5);
        String actual = o.toString();
        String pi = "<abcde>.insert('x',5) -> <abcdex>";
        assertEquals(pi, expected, actual);
    }

}