// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * Static Factory method(s) that return an object with a specified state. Should
 * be abstract since it only has static methods but Web-CAT flags code coverage
 * because it's not instantiated.
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListFactory {

    /**
     * Returns an object of the given state s.
     * 
     * @param s
     *            state string of the desired object
     * @return object with state s
     */
    public static List build(String s) {

        // instantiate the object to be returned.
        List o = new CharLinkList();

        // set o to the specified state (s)
        switch (s) {
            case "<>" :
                // no need to do anything here
                break;
            case "<abc>" :
                o.insert('c', 0); 
                o.insert('b', 0); 
                o.insert('a', 0); 
                break;
            case "<abcde>" :
                o.insert('e', 0); 
                o.insert('d', 0); 
                o.insert('c', 0); 
                o.insert('b', 0); 
                o.insert('a', 0); 
                break;
            case "<a>" :
                o.insert('a', 0); 
                break;
            case "<abcdf>" :
                o.insert('f', 0); 
                o.insert('d', 0); 
                o.insert('c', 0); 
                o.insert('b', 0); 
                o.insert('a', 0); 
                break;

                
            // s was not one of the states specified in Asg List
            default:
                String fmt =
                    "Problem in ListFactory.java: unhandled state(%s)";
                throw new IllegalArgumentException(String.format(fmt, s));
        }

        return o;
    }

}