import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * These are the "ValueFalse" tests of the group "EqualsObject"
 * of the "List" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListEqualsObjectValueFalseTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <>.equals(x) == false
     */
    @Test
    public void empty() {
        List o = ListFactory.build("<>");
        List x = ListFactory.build("<abc>");
        boolean expected = false;
        boolean actual = o.equals(x);
        String pi = "<>.equals(x) == false";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a>.equals(x) == false
     */
    @Test
    public void one() {
        List o = ListFactory.build("<a>");
        List x = ListFactory.build("<abc>");
        boolean expected = false;
        boolean actual = o.equals(x);
        String pi = "<a>.equals(x) == false";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.equals(x) == false
     */
    @Test
    public void fiveDifLen() {
        List o = ListFactory.build("<abcde>");
        List x = ListFactory.build("<abc>");
        boolean expected = false;
        boolean actual = o.equals(x);
        String pi = "<abcde>.equals(x) == false";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.equals(x) == false
     */
    @Test
    public void fiveDiffElt() {
        List o = ListFactory.build("<abcde>");
        List x = ListFactory.build("<abcdf>");
        boolean expected = false;
        boolean actual = o.equals(x);
        String pi = "<abcde>.equals(x) == false";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.equals(null) == false
     */
    @Test
    public void fiveNull() {
        List o = ListFactory.build("<abcde>");
        boolean expected = false;
        boolean actual = o == null;
        String pi = "<abcde>.equals(null) == false";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.equals("not a list") == false
     */
    @Test
    public void fiveNotList() {
        List o = ListFactory.build("<abcde>");
        boolean expected = false;
        boolean actual = o.equals("not a list");
        String pi = "<abcde>.equals(\"not a list\") == false";
        assertEquals(pi, expected, actual);
    }

}