import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import edu.cnu.cnuassert.CNUThrowingRunnable;
//
// correct these imports if needed and add any missing exception imports here.
//

// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * These are the "Exception" tests of the group "GetInt"
 * of the "List" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListGetIntExceptionTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <>.get(0) !! IllegalArgumentException
     */
    @Test
    public void get0thFrom0() {
        List o = ListFactory.build("<>");
        Class<? extends Throwable> expected = IllegalArgumentException.class;
        CNUThrowingRunnable l = () -> o.get(0);
        String pi = "<>.get(0) !! IllegalArgumentException";
        assertThrows(pi, expected, l);
    }


    /**
     * <a>.get(1) !! IllegalArgumentException
     */
    @Test
    public void get1thFrom1() {
        List o = ListFactory.build("<a>");
        Class<? extends Throwable> expected = IllegalArgumentException.class;
        CNUThrowingRunnable l = () -> o.get(1);
        String pi = "<a>.get(1) !! IllegalArgumentException";
        assertThrows(pi, expected, l);
    }


    /**
     * <abcde>.get(-1) !! IllegalArgumentException
     */
    @Test
    public void getNeg1thFrom5() {
        List o = ListFactory.build("<abcde>");
        Class<? extends Throwable> expected = IllegalArgumentException.class;
        CNUThrowingRunnable l = () -> o.get(-1);
        String pi = "<abcde>.get(-1) !! IllegalArgumentException";
        assertThrows(pi, expected, l);
    }


    /**
     * <abcde>.get(5) !! IllegalArgumentException
     */
    @Test
    public void get6thFrom5() {
        List o = ListFactory.build("<abcde>");
        Class<? extends Throwable> expected = IllegalArgumentException.class;
        CNUThrowingRunnable l = () -> o.get(5);
        String pi = "<abcde>.get(5) !! IllegalArgumentException";
        assertThrows(pi, expected, l);
    }

}