import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * These are the "State" tests of the group "SwapIntInt"
 * of the "List" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListSwapIntIntStateTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <abcde>.swap(0,0) -> <abcde>
     */
    @Test
    public void swap00() {
        List o = ListFactory.build("<abcde>");
        String expected = "<abcde>";
        o.swap(0, 0);
        String actual = o.toString();
        String pi = "<abcde>.swap(0,0) -> <abcde>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.swap(2,2) -> <abcde>
     */
    @Test
    public void swap22() {
        List o = ListFactory.build("<abcde>");
        String expected = "<abcde>";
        o.swap(2, 2);
        String actual = o.toString();
        String pi = "<abcde>.swap(2,2) -> <abcde>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.swap(4,4) -> <abcde>
     */
    @Test
    public void swap44() {
        List o = ListFactory.build("<abcde>");
        String expected = "<abcde>";
        o.swap(4, 4);
        String actual = o.toString();
        String pi = "<abcde>.swap(4,4) -> <abcde>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.swap(0,4) -> <ebcda>
     */
    @Test
    public void swap04() {
        List o = ListFactory.build("<abcde>");
        String expected = "<ebcda>";
        o.swap(0, 4);
        String actual = o.toString();
        String pi = "<abcde>.swap(0,4) -> <ebcda>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.swap(4,0) -> <ebcda>
     */
    @Test
    public void swap40() {
        List o = ListFactory.build("<abcde>");
        String expected = "<ebcda>";
        o.swap(4, 0);
        String actual = o.toString();
        String pi = "<abcde>.swap(4,0) -> <ebcda>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.swap(1,3) -> <adcbe>
     */
    @Test
    public void swap13() {
        List o = ListFactory.build("<abcde>");
        String expected = "<adcbe>";
        o.swap(1, 3);
        String actual = o.toString();
        String pi = "<abcde>.swap(1,3) -> <adcbe>";
        assertEquals(pi, expected, actual);
    }

}