import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * These are the "Value" tests of the group "GetInt"
 * of the "List" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListGetIntValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <a>.get(0) == 'a'
     */
    @Test
    public void getReturnsElt0OfOne() {
        List o = ListFactory.build("<a>");
        char expected = 'a';
        char actual = o.get(0);
        String pi = "<a>.get(0) == 'a'";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.get(0) == 'a'
     */
    @Test
    public void getReturnsElt0OfFive() {
        List o = ListFactory.build("<abcde>");
        char expected = 'a';
        char actual = o.get(0);
        String pi = "<abcde>.get(0) == 'a'";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.get(2) == 'c'
     */
    @Test
    public void getReturnsElt2OfFive() {
        List o = ListFactory.build("<abcde>");
        char expected = 'c';
        char actual = o.get(2);
        String pi = "<abcde>.get(2) == 'c'";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.get(4) == 'e'
     */
    @Test
    public void getReturnsElt4OfFive() {
        List o = ListFactory.build("<abcde>");
        char expected = 'e';
        char actual = o.get(4);
        String pi = "<abcde>.get(4) == 'e'";
        assertEquals(pi, expected, actual);
    }

}