import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * These are the "State" tests of the group "RemoveInt"
 * of the "List" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListRemoveIntStateTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <abcde>.remove(0) -> <bcde>
     */
    @Test
    public void removeFirst() {
        List o = ListFactory.build("<abcde>");
        String expected = "<bcde>";
        o.remove(0);
        String actual = o.toString();
        String pi = "<abcde>.remove(0) -> <bcde>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.remove(2) -> <abde>
     */
    @Test
    public void removeMiddle() {
        List o = ListFactory.build("<abcde>");
        String expected = "<abde>";
        o.remove(2);
        String actual = o.toString();
        String pi = "<abcde>.remove(2) -> <abde>";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.remove(4) -> <abcd>
     */
    @Test
    public void removeLast() {
        List o = ListFactory.build("<abcde>");
        String expected = "<abcd>";
        o.remove(4);
        String actual = o.toString();
        String pi = "<abcde>.remove(4) -> <abcd>";
        assertEquals(pi, expected, actual);
    }

}