import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG List on 20250124
/**
 * These are the "Value" tests of the group "Size"
 * of the "List" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20250123
 */
public class ListSizeValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <>.size() == 0
     */
    @Test
    public void empty() {
        List o = ListFactory.build("<>");
        int expected = 0;
        int actual = o.size();
        String pi = "<>.size() == 0";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a>.size() == 1
     */
    @Test
    public void one() {
        List o = ListFactory.build("<a>");
        int expected = 1;
        int actual = o.size();
        String pi = "<a>.size() == 1";
        assertEquals(pi, expected, actual);
    }


    /**
     * <abcde>.size() == 5
     */
    @Test
    public void five() {
        List o = ListFactory.build("<abcde>");
        int expected = 5;
        int actual = o.size();
        String pi = "<abcde>.size() == 5";
        assertEquals(pi, expected, actual);
    }

}