// GENERATED BY ATA3.0/20240730 FROM ASG CBList on 20250214
/**
 * Static Factory method(s) that return an object with a specified state. Should
 * be abstract since it only has static methods but Web-CAT flags code coverage
 * because it's not instantiated.
 * 
 * @author asand
 * @version 20250214
 */
public class CBListFactory {

    /**
     * Returns an object of the given state s.
     * 
     * @param s
     *            state string of the desired object
     * @return object with state s
     */
    public static CBList build(String s) {

        // instantiate the object to be returned.
        CBList o = new CharArrayCBList();

        // set o to the specified state (s)
        switch (s) {
            case "<a,b,c,d,e|>" :
                o = o.make("<a,b,c,d,e|>");
                break;
            case "<|a>" :
                o = o.make("<|a>");
                break;
            case "<a|b,c>" :
                o = o.make("<a|b,c>");
                break;
            case "<>" :
                o = o.make("<>");
                break;
            case "<a,b,c|>" :
                o = o.make("<a,b,c|>");
                break;
            case "<a|b>" :
                o = o.make("<a|b>");
                break;
            case "<a,b,c,d|e>" :
                o = o.make("<a,b,c,d|e>");
                break;
            case "<a,b|c>" :
                o = o.make("<a,b|c>");
                break;
            case "<a,b,c|d,e>" :
                o = o.make("<a,b,c|d,e>");
                break;
            case "<a,b|c,d>" :
                o = o.make("<a,b|c,d>");
                break;
            case "<|a,b,c,d,e>" :
                o = o.make("<|a,b,c,d,e>");
                break;
            case "<|a,b,c,d,f>" :
                o = o.make("<|a,b,c,d,f>");
                break;
            case "<a,b|c,d,e>" :
                o = o.make("<a,b|c,d,e>");
                break;
            case "<|a,b,c>" :
                o = o.make("<|a,b,c>");
                break;
            case "<a|>" :
                o = o.make("<a|>");
                break;
            case "<|>" :
                o = o.make("<|>");
                break;

            // s was not one of the states specified in Asg CBList
            default:
                String fmt =
                    "Problem in CBListFactory.java: unhandled state(%s)";
                throw new IllegalArgumentException(String.format(fmt, s));
        }

        return o;
    }

}