import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG CBList on 20250214
/**
 * These are the "Value" tests of the group "ToString"
 * of the "CBList" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250214
 */
public class CBListToStringValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <|>.toString() == "<|>;"
     */
    @Test
    public void empty() {
        CBList o = CBListFactory.build("<|>");
        String expected = "<|>";
        String actual = o.toString();
        String pi = "<|>.toString() == \"<|>\"";
        assertEquals(pi, expected, actual);
    }


    /**
     * <|a>.toString() == "<|a>;"
     */
    @Test
    public void one() {
        CBList o = CBListFactory.build("<|a>");
        String expected = "<|a>";
        String actual = o.toString();
        String pi = "<|a>.toString() == \"<|a>\"";
        assertEquals(pi, expected, actual);
    }


    /**
     * <|a,b,c,d,e>.toString() == "<|a,b,c,d,e>;"
     */
    @Test
    public void five() {
        CBList o = CBListFactory.build("<|a,b,c,d,e>");
        String expected = "<|a,b,c,d,e>";
        String actual = o.toString();
        String pi = "<|a,b,c,d,e>.toString() == \"<|a,b,c,d,e>\"";
        assertEquals(pi, expected, actual);
    }

}