import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG CBList on 20250214
/**
 * These are the "Value" tests of the group "Pos"
 * of the "CBList" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250214
 */
public class CBListPosValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <|>.pos() == 0
     */
    @Test
    public void empty() {
        CBList o = CBListFactory.build("<|>");
        int expected = 0;
        int actual = o.pos();
        String pi = "<|>.pos() == 0";
        assertEquals(pi, expected, actual);
    }


    /**
     * <|a>.pos() == 0
     */
    @Test
    public void oneatzero() {
        CBList o = CBListFactory.build("<|a>");
        int expected = 0;
        int actual = o.pos();
        String pi = "<|a>.pos() == 0";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a|b>.pos() == 1
     */
    @Test
    public void twoatone() {
        CBList o = CBListFactory.build("<a|b>");
        int expected = 1;
        int actual = o.pos();
        String pi = "<a|b>.pos() == 1";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,c|d,e>.pos() == 3
     */
    @Test
    public void fiveatthree() {
        CBList o = CBListFactory.build("<a,b,c|d,e>");
        int expected = 3;
        int actual = o.pos();
        String pi = "<a,b,c|d,e>.pos() == 3";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,c,d,e|>.pos() == 5
     */
    @Test
    public void fiveatfive() {
        CBList o = CBListFactory.build("<a,b,c,d,e|>");
        int expected = 5;
        int actual = o.pos();
        String pi = "<a,b,c,d,e|>.pos() == 5";
        assertEquals(pi, expected, actual);
    }

}