import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG CBList on 20250214
/**
 * These are the "Value" tests of the group "AsArray"
 * of the "CBList" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250214
 */
public class CBListAsArrayValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <|>.asArray() == x
     */
    @Test
    public void emptyList() {
        CBList o = CBListFactory.build("<|>");
        char[] x = {};
        char[] expected = x;
        char[] actual = o.asArray();
        String pi = "<|>.asArray() == x";
        assertArrayEquals(pi, expected, actual);
    }


    /**
     * <|a>.asArray() == x
     */
    @Test
    public void oneList() {
        CBList o = CBListFactory.build("<|a>");
        char[] x = {'a'};
        char[] expected = x;
        char[] actual = o.asArray();
        String pi = "<|a>.asArray() == x";
        assertArrayEquals(pi, expected, actual);
    }


    /**
     * <|a,b,c>.asArray() == x
     */
    @Test
    public void threelist() {
        CBList o = CBListFactory.build("<|a,b,c>");
        char[] x = {'a', 'b', 'c'};
        char[] expected = x;
        char[] actual = o.asArray();
        String pi = "<|a,b,c>.asArray() == x";
        assertArrayEquals(pi, expected, actual);
    }

}