import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG CBList on 20250214
/**
 * These are the "Value" tests of the group "Get"
 * of the "CBList" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250214
 */
public class CBListGetValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <a>.get() == 'a'
     */
    @Test
    public void getReturns() {
        CBList o = CBListFactory.build("<|a>");
        char expected = 'a';
        char actual = o.get();
        String pi = "<|a>.get() == 'a'";
        assertEquals(pi, expected, actual);
    }


    /**
     * <|a,b,c,d,e>.get() == 'a'
     */
    @Test
    public void getReturnsatone() {
        CBList o = CBListFactory.build("<|a,b,c,d,e>");
        char expected = 'a';
        char actual = o.get();
        String pi = "<|a,b,c,d,e>.get() == 'a'";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b|c,d,e>.get() == 'c'
     */
    @Test
    public void getReturnsattwo() {
        CBList o = CBListFactory.build("<a,b|c,d,e>");
        char expected = 'c';
        char actual = o.get();
        String pi = "<a,b|c,d,e>.get() == 'c'";
        assertEquals(pi, expected, actual);
    }


    /**
     * <a,b,c,d|e>.get() == 'e'
     */
    @Test
    public void getReturnsatfour() {
        CBList o = CBListFactory.build("<a,b,c,d|e>");
        char expected = 'e';
        char actual = o.get();
        String pi = "<a,b,c,d|e>.get() == 'e'";
        assertEquals(pi, expected, actual);
    }

}