import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG CBList on 20250214
/**
 * These are the "Value" tests of the group "MakeString"
 * of the "CBList" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author asand
 * @version 20250214
 */
public class CBListMakeStringValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <|>.make("<a|b,c") == d
     */
    @Test
    public void example() {
        CBList o = CBListFactory.build("<|>");
        CBList d = CBListFactory.build("<a|b,c>");
        CBList expected = d;
        CBList actual = o.make("<a|b,c");
        String pi = "<|>.make(\"<a|b,c\") == d";
        assertEquals(pi, expected, actual);
    }


    /**
     * <|>.make("<|>") == d
     */
    @Test
    public void empty() {
        CBList o = CBListFactory.build("<|>");
        CBList d = CBListFactory.build("<|>");
        CBList expected = d;
        CBList actual = o.make("<|>");
        String pi = "<|>.make(\"<|>\") == d";
        assertEquals(pi, expected, actual);
    }


    /**
     * <|>.make("<a|>") == d
     */
    @Test
    public void one() {
        CBList o = CBListFactory.build("<|>");
        CBList d = CBListFactory.build("<a|>");
        CBList expected = d;
        CBList actual = o.make("<a|>");
        String pi = "<|>.make(\"<a|>\") == d";
        assertEquals(pi, expected, actual);
    }


    /**
     * <|a>.make("<a,b,c|>") == d
     */
    @Test
    public void onenotempty() {
        CBList o = CBListFactory.build("<|a>");
        CBList d = CBListFactory.build("<a,b,c|>");
        CBList expected = d;
        CBList actual = o.make("<a,b,c|>");
        String pi = "<|a>.make(\"<a,b,c|>\") == d";
        assertEquals(pi, expected, actual);
    }

}