// GENERATED BY ATA3.0/20240730 FROM ASG RationalAsg on 20250128
/**
 * Static Factory method(s) that return an object with a specified state. Should
 * be abstract since it only has static methods but Web-CAT flags code coverage
 * because it's not instantiated.
 * 
 * @author acsiochi
 * @version 20240729
 */
public class RationalFactory {

    /**
     * Returns an object of the given state s.
     * 
     * @param s
     *            state string of the desired object
     * @return object with state s
     */
    public static Rational build(String s) {


        // instantiate the object to be returned.
        
        Rational o = new IntRational();

        // set o to the specified state (s)
        switch (s) {
            case "<1,1>" :
                o.set(1, 1);
                break;
            case "<0,3>" :
                o.set(0, 3);
                break;
            case "<2,3>" :
                o.set(2, 3);
                break;
            case "<0,1>" :
                o.set(0, 1);
                break;
            case "<3,1>" :
                o.set(3, 1);
                break;
            case "<0,2>" :
                o.set(0, 2);
                break;
            case "<12,9>" :
                o.set(12, 9);
                break;
            case "<5,3>" :
                o.set(5, 3);
                break;
            case "<4,9>" :
                o.set(4, 9);
                break;

            // s was not one of the states specified in Asg RationalAsg
            default:
                String fmt =
                    "Problem in RationalFactory.java: unhandled state(%s)";
                throw new IllegalArgumentException(String.format(fmt, s));
        }

        return o;
    }

}