import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import edu.cnu.cnuassert.CNUThrowingRunnable;
//
// correct these imports if needed and add any missing exception imports here.
//

// GENERATED BY ATA3.0/20240730 FROM ASG RationalAsg on 20250128
/**
 * These are the "Exception" tests of the group "setString"
 * of the "RationalAsg" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20240729
 */
public class RationalAsgSetStringExceptionTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <0,1>.set("<1,0>") !! IllegalArgumentException
     */
    @Test
    public void dto0() {
        Rational o = RationalFactory.build("<0,1>");
        Class<? extends Throwable> expected = IllegalArgumentException.class;
        CNUThrowingRunnable l = () -> o.set("<1,0>");
        String pi = "<0,1>.set(\"<1,0>\") !! IllegalArgumentException";
        assertThrows(pi, expected, l);
    }

}