import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG RationalAsg on 20250128
/**
 * These are the "Value" tests of the group "add"
 * of the "RationalAsg" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20240729
 */
public class RationalAsgAddValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <0,1>.add(r) == p
     */
    @Test
    public void def() {
        Rational o = RationalFactory.build("<0,1>");
        Rational r = RationalFactory.build("<2,3>");
        Rational p = RationalFactory.build("<2,3>");
        Rational expected = p;
        Rational actual = o.add(r);
        String pi = "<0,1>.add(r) == p";
        assertEquals(pi, expected, actual);
    }


    /**
     * <2,3>.add(r) == p
     */
    @Test
    public void twoThree() {
        Rational o = RationalFactory.build("<2,3>");
        Rational r = RationalFactory.build("<2,3>");
        Rational p = RationalFactory.build("<12,9>");
        Rational expected = p;
        Rational actual = o.add(r);
        String pi = "<2,3>.add(r) == p";
        assertEquals(pi, expected, actual);
    }


    /**
     * <2,3>.add(i) == e
     */
    @Test
    public void me() {
        Rational o = RationalFactory.build("<2,3>");
        Rational i = RationalFactory.build("<1,1>");
        Rational e = RationalFactory.build("<5,3>");
        Rational expected = e;
        Rational actual = o.add(i);
        String pi = "<2,3>.add(i) == e";
        assertEquals(pi, expected, actual);
    }

}