import static edu.cnu.cnuassert.CNUassert.*;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
// GENERATED BY ATA3.0/20240730 FROM ASG RationalAsg on 20250128
/**
 * These are the "Value" tests of the group "getNum"
 * of the "RationalAsg" assignment.
 * 
 * Each test method below corresponds to one test statement
 * (i.e.,problem instance).
 * 
 * @author acsiochi
 * @version 20240729
 */
public class RationalAsgGetNumValueTests {

// ========== [ START OF CNUassert required code. DO NOT CHANGE ] =============
    /** gets name of executing method */
    @Rule
    public TestName name = new TestName();

    /** Initializes CNUassert with this classname. */
    @BeforeClass
    public static void setUp() {
        initTestSet(
            java.lang.invoke.MethodHandles.lookup().lookupClass()
                .getSimpleName());
    }


    /** Tells CNUassert the name of the currently executing test method. */
    @Before
    public void testinit() {
        initTest(this.name.getMethodName());
    }


    /** Tells CNUassert to stop these tests then print the log. */
    @AfterClass
    public static void done() {
        System.out.println(closeTests());
    }
// ======= [ END OF CNUassert required code. DO NOT CHANGE THE ABOVE] ========

//+---------------------------------------------------------+
//|  Generated test methods below. Don't modify them.       |
//|  Modify asg file instead. Report bugs to siochi@acm.org |
//+---------------------------------------------------------+
// === Problem Instances - one JUnit test per problem instance ===

    /**
     * <0,1>.getNum() == 0
     */
    @Test
    public void nIs0() {
        Rational o = RationalFactory.build("<0,1>");
        int expected = 0;
        int actual = o.getNum();
        String pi = "<0,1>.getNum() == 0";
        assertEquals(pi, expected, actual);
    }


    /**
     * <3,1>.getNum() == 3
     */
    @Test
    public void nIs3() {
        Rational o = RationalFactory.build("<3,1>");
        int expected = 3;
        int actual = o.getNum();
        String pi = "<3,1>.getNum() == 3";
        assertEquals(pi, expected, actual);
    }

}